services:

  prefect-server:
    image: prefecthq/prefect:3-latest
    restart: unless-stopped
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "127.0.0.1:4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    environment:
      PREFECT_UI_ENABLED: "true"
      PREFECT_SERVER_ANALYTICS_ENABLED: "false"

volumes:
  prefect_data:
